services:

  backend:
    build: ./backend
    ports:
      - "5000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notes
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"